# Generated by Django 5.0.4 on 2024-05-01 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_alter_item_updated_at'),
        ('user', '0002_alter_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total_Price')),
                ('full_name', models.CharField(db_index=True, max_length=50, verbose_name='Full_Name')),
                ('address_line1', models.CharField(db_index=True, max_length=50, verbose_name='Address_line1')),
                ('address_line2', models.CharField(db_index=True, max_length=50, verbose_name='Address_line2')),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='City')),
                ('state', models.CharField(db_index=True, max_length=50, verbose_name='State')),
                ('postal_code', models.IntegerField(verbose_name='Postal_code')),
                ('country', models.CharField(db_index=True, max_length=50, verbose_name='Country')),
                ('telephone', models.IntegerField(verbose_name='Telephone')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
